// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naclmhkxanjwbultlhxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hY2xtaGt4YW5qd2J1bHRsaHh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NTQwNDMsImV4cCI6MjA2ODUzMDA0M30.bDL4oSpsM0EFzOKt90l1bt5SWwFM22WbiempKYy5dzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});